serve:
  proxy:
    port: 4200 # run the proxy at port 4455
  api:
    port: 4458 # run the api at port 4456

access_rules:
  repositories:
    - file:///etc/config/oathkeeper/rules.json
    # - file:///home/jthijs/devel/aloxy/oathkeeper/.docker_compose/rules.json

errors:
  fallback:
    - json
  handlers:
    json:
      enabled: true
      config:
        verbose: true
    redirect:
      enabled: true
      config:
        to: https://www.ory.sh/docs

mutators:
  header:
    enabled: true
    config:
      headers:
        Cookie: "insert cookie"
        Origin: "http://localhost:4200"
        Referer: "http://localhost:4200/"
  noop:
    enabled: true

authorizers:
  allow:
    enabled: true

authenticators:
  noop:
    enabled: true

log:
  leak_sensitive_values: true